### ISSUE TITLE
Set inlineStyles..onlyMatchedOnce to false

### ISSUE THREAD

**Issue by Slion** [konsumer/inkscape-svgo#5]
Is there a way to set SVGO extensions parameters without rebuilding the project?
I would need to set inlineStyles.onlyMatchedOnce to false.

See:
https://github.com/svg/svgo/issues/1259
https://github.com/svg/svgo/issues/1257

**Comment by Slion** [comment]
Maybe this could be the solution:
https://github.com/svg/svgo/issues/636

**Comment by konsumer** [comment]
I'm not sure I understand. None of those linked issues seem to apply to this repo. If you mean you'd like to change the defaults in the inkscape dialog, go find [inkscape-svgo.inx](https://github.com/konsumer/inkscape-svgo/blob/master/inkscape-svgo.inx) and you can edit it to have whatever defaults you like.

**Comment by Slion** [comment]
Yes, I did modify the INX to pass the parameters I needed. Though svgo is complaining about malformed JSON when using that config on the command line. Not an issue with this repo though. Modifying INX is pretty cool I could even add a string parameter for the config.
